# NB: don't set `language: haskell` here

sudo: false

env:
  - GHCVER=7.10.2 STACK_YAML=stack.yaml
# 2015.07.20, builds with GHC HEAD fail: do not waste energy
# - GHCVER=head STACK_YAML=stack.yaml
#
# matrix:
#   allow_failures:
#     - env: GHCVER=head STACK_YAML=stack.yaml

before_install:
  # put GHC in the path
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH

  # install stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.10.0/stack-0.1.10.0-linux-x86_64.tar.gz | gunzip > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack

  # log versions
  - stack --version
  - ghc --version

install:
  - ./.travis_long.sh stack --no-terminal --skip-ghc-check setup
  - ./.travis_long.sh stack --no-terminal --skip-ghc-check init
  - ./.travis_long.sh stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
#    - ghc-head
